services:
  # A Docker web service
  - type: web
    name: FilterBot
    env: python
    startCommand: python3 main.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/Learningbots79/MentionAll_Bot # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: Professor-99 # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
